### ISSUE TITLE
Open EPUBs from Overdrive can't be returned

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/circulation#447] opened 2017-01-12 15:49 UTC
Overdrive has some books available in Open EPUB format (example: https://brooklyn.overdrive.com/media/484622). They don't have DRM so they can't be returned through Adobe. There's a return link in the OPDS entries, but it doesn't actually return the book.

I'm not sure if it's possible to return these, or if we should remove the links.

**Comment by leonardr** [comment] 2017-01-19 14:11
overdrive.py defines a checkin() method that calls the Overdrive API to delete the loan, so it should be working. Either that method doesn't do what we think it does, or the problem is on Overdrive's side.

**Comment by leonardr** [comment] 2018-05-30 14:03
Duplicate of https://github.com/NYPL-Simplified/circulation/issues/860, which has been fixed.

**Closed by leonardr** 2018-05-30 14:03 UTC
